import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";

const manrope = Manrope({
  weight: ["200", "300", "400", "500", "600"], // Thin, Regular, Medium
  subsets: ["latin"],
  display: "swap",
  variable: "--font-manrope",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.className} bg-white min-w-[375px] text-neutral-900 font-sans subpixel-antialiased} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
